server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    # url rewrite 문제 해결
    session:
      tracking-modes: cookie
      timeout: 30m
  port: 8080

spring:
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true

  datasource:
    url: jdbc:mysql://localhost:3306/socialize # AWS 호스트
    username: root # AWS USERNAME
    password: Root1234 # AWS PASSWORD
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
  sql:
    init:
      data-locations:
        - classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
    defer-datasource-initialization: false

  # m3u8 을 비디오 타입으로 하기위해 추가
  http:
    media-types:
      hls:
        - application/vnd.apple.mpegurl